name: 'VMRaid Assets'

on:
  push:
    branches: [ develop ]

jobs:
  build-dev-and-publish:
    name: 'Build and Publish Assets for Development'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'vmraid'
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Set up chair and build assets
        run: |
          npm install -g yarn
          pip3 install -U vmraid-chair
          chair init vmraid-chair --no-procfile --no-backups --skip-assets --skip-redis-config-generation --python $(which python) --vmraid-path $GITHUB_WORKSPACE/vmraid
          cd vmraid-chair && chair build

      - name: Package assets
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          tar -cvpzf $GITHUB_WORKSPACE/build/$GITHUB_SHA.tar.gz ./vmraid-chair/sites/assets/vmraid/dist

      - name: Publish assets to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: 'assets.vmraidframework.com'
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ASSETS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ASSETS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: 'http://s3.fr-par.scw.cloud'
          AWS_REGION: 'fr-par'
          SOURCE_DIR: '$GITHUB_WORKSPACE/build'
